export enum events {
    isReady=            'isReady',
    ready=              'ready',
    hitBreakpoint=      'hitBreakpoint',
    addBreakpoints=     'addBreakpoints',
    removeBreakpoints=  'removeBreakpoints',
    clearAllBreakpoints='clearAllBreakpoints',
    toggleBreakpoint=   'toggleBreakpoint',
    addFile=            'addFile',
    addFiles=           'addFiles',
    start=              'start',
    stop=               'stop',
    continue=           'continueExecution',
    stepInto=           'stepInto',
    stepOut=            'stepOut',
    stepOver=           'stepOver',
    getVarList=         'getVarList',
    restart=            'restart',
    kill=               'EXECUTE_ORDER_66',
    message=            'message',
  }
